server:
  port: 9000
  servlet:
    context-path: "/api"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture-editor?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:/sql/*.xml
  type-aliases-package: com.entity
  global-config:
    db-config:
      id-type: auto # 主键策略:
#     naming-strategy: camelCase  #驼峰、 默认数据库为_


# 使用还需接口依赖相关注释
#mybatis:
#  type-aliases-package: com.entity
#  mapper-locations: classpath:/mapper/*.xml

##server.port=9000
## ????????
#server.servlet.context-path=/api
## ???????????
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=3MB
#spring.servlet.multipart.max-request-size=10MB
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/picture-editor?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=123456